name: Deploy Infrastructure

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: tf-runner

    steps:
      - uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: get PWD
        run: pwd

      # Generates an execution plan for Terraform
      - name: terragrunt Plan
        run: terragrunt plan-all